# RoboDK Python Intermediate file to generate robot programs.
# Program name: Attach
# This file requires the post processor: 
#   Universal_Robots
# to generate your robot program.
# This is a temporary file and you can delete it once you have generated your program.
# 
# Post processor documentation: https://robodk.com/doc/en/PythonAPI/postprocessor.html

import sys
import os
import robodk
sys.path.append(os.path.abspath(r"""D:/Program Files/RoboDK/Posts/""")) # temporarily add path to POSTS folder

from Universal_Robots import *

try:
  from robodk.robomath import PosePP as p
except:
  # This will be removed in future versions of RoboDK
  from robodk import PosePP as p


print('Total instructions: 1')
r = RobotPost(r"""Universal_Robots""",r"""UR5e""",6, axes_type=['R','R','R','R','R','R'], native_name=r"""UR5e""", ip_com=r"""127.0.0.1""", api_port=20500, prog_ptr=2215842313456, robot_ptr=2215762595808)

r.ProgStart(r"""Attach""")
r.RunMessage(r"""Program generated by RoboDK v5.7.0 for UR5e on 24/03/2024 21:51:09""",True)
r.RunMessage(r"""Using nominal kinematics.""",True)
r.RunMessage(r"""Attach to Schunk""",True)
r.MoveL(p(300,150,339.565,0,0,-180),[-279.194,-119.117,-71.85,-79.0326,90,-9.19396],[0,1,0])
r.ProgFinish(r"""Attach""")
r.ProgSave(r"""C:/Users/rockw/Documents/RoboDK/Programs/""",r"""Attach""",False,r"""notepad.exe""")
